apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: prereqs
  # interval: 5m
  interval: 10s
  path: ./flux/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
