apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prereqs
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux/prereqs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
