---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: newrelic
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm-charts.newrelic.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic-bundle
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: nri-bundle
      # Newest `version` here:
      # https://github.com/newrelic/helm-charts/blob/master/charts/nri-bundle/Chart.yaml
      version: "5.0.28"
      sourceRef:
        kind: HelmRepository
        name: newrelic
        namespace: flux-system
      interval: 1m
  # Default values:
  # https://github.com/newrelic/helm-charts/blob/master/charts/nri-bundle/values.yaml
  values:
    global:
      cluster: ctf-workshop
      customSecretName: newrelic-license
      customSecretLicenseKey: LICENSE_KEY

    newrelic-infrastructure:
      enabled: true

    nri-metadata-injection:
      enabled: false
