---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: wordpress
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/wordpress
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: wordpress
      # Newest `version` here:
      # https://github.com/bitnami/charts/blob/main/bitnami/wordpress/Chart.yaml
      version: "18.1.23"
      sourceRef:
        kind: HelmRepository
        name: wordpress
        namespace: flux-system
      interval: 1m
  # Default values:
  # https://github.com/bitnami/charts/blob/main/bitnami/wordpress/values.yaml
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-production
      hostname: wordpress.silly.hair
      tls: true
