---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: multi-juicer
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/juice-shop/multi-juicer/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multi-juicer
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: multi-juicer
      # Newest `version` here:
      # https://github.com/juice-shop/multi-juicer/blob/main/helm/multi-juicer/Chart.yaml
      version: "6.0.0"
      sourceRef:
        kind: HelmRepository
        name: multi-juicer
        namespace: flux-system
      interval: 1m
  # Default values:
  # https://github.com/juice-shop/multi-juicer/blob/main/helm/multi-juicer/values.yaml
  values:
    juiceShop:
      maxInstances: 20
      resources:
        requests:
          cpu: 200m
          memory: 300Mi
        limits:
          cpu: 200m
          memory: 300Mi

    balancer:
      metrics:
        enabled: true
        # Create dashboards in ConfigMaps for Grafana to pick up and import
        dashboards:
          enabled: true

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-staging
      hosts:
        - host: ctf.silly.hair
          paths:
            - "/"
      tls:
        - hosts:
            - ctf.silly.hair
          secretName: tls-secret
